Feature/complete workflow
wistcc/werewolf-moderator pull request #19
Opened 2017-04-05 02:46 UTC by wOvalle

2017-04-05 05:32 UTC, vetom approved these changes

2017-04-08 15:22 UTC, wistcc requested changes
LVGTM. Just a few comments.

2017-04-08 15:22 UTC, wistcc commented on src/js/components/Wizard.js
> +        value: 1,
I think that this is not correct, isn't it?

2017-04-08 15:22 UTC, wistcc commented on src/js/pages/Cards.js
> +            <label><input type="checkbox" onChange={this.setVisibility} checked={c.visible || false} name={c.key} /> {c.key}</label>
`c.visible || false` is not enough `c.visible`?

2017-04-08 15:22 UTC, wistcc commented on src/js/components/Wizard.js
> +const DEFAULT_GAME_MODE = 'balanced';
Probably we should create another file with this `'balanced`', 'chaos` and `'basic'`.

2017-04-08 15:22 UTC, wistcc commented on src/js/pages/Cards.js
> +              <button onClick={this.props.startGame.bind(this, "balanced")} className="btn btn-default col-md-4 col-md-offset-1 col-xs-12 btn-space"><i class="fa fa-balance-scale" aria-hidden="true">
Probably we should create another file with this `'balanced`', 'chaos` and `'basic'`.

2017-04-08 15:22 UTC, wistcc commented on src/js/pages/Home.js
> +              <button onClick={this.props.startGame.bind(this, "balanced")} className="btn btn-default col-md-5 col-md-offset-2"><i class="fa fa-balance-scale" aria-hidden="true"></i> Quick Balanced<
Probably we should create another file with this `'balanced`', 'chaos` and `'basic'`.

2017-04-08 15:22 UTC, wistcc commented on src/js/pages/Cards.js
> +              <button onClick={this.props.startGame.bind(this, "chaos")} className="btn btn-default col-md-4 col-md-offset-1 col-xs-12 btn-space"><i class="fa fa-arrows" aria-hidden="true"></i> Quick
Probably we should create another file with this `'balanced`', 'chaos` and `'basic'`.

2017-04-08 15:22 UTC, wistcc commented on src/js/pages/Home.js
> +              <button onClick={this.props.startGame.bind(this, "chaos")} className="btn btn-default col-md-5"><i class="fa fa-arrows" aria-hidden="true"></i> Quick Chaos</button>
Probably we should create another file with this `'balanced`', 'chaos` and `'basic'`.

2017-04-08 15:22 UTC, wistcc commented on src/js/services/werewolf.js
> +        return Object.keys(cards).map(_ => {return {key: _, value: cards[_]}});
I'm a full fan of always having very descriptive names!

2017-04-08 17:29 UTC, wOvalle commented on src/js/components/Wizard.js
> +        value: 1,
What do you mean?

2017-04-08 17:43 UTC, wOvalle commented
@wistcc Since the original motive of this pr was to implement the full workflow of the project, I created two issues with enhancements ( #22 and #23 ) to take care of the standardization of gameTypes and languages.

2017-04-08 17:43 UTC, wOvalle commented on src/js/pages/Home.js
> +              <button onClick={this.props.startGame.bind(this, "balanced")} className="btn btn-default col-md-5 col-md-offset-2"><i class="fa fa-balance-scale" aria-hidden="true"></i> Quick Balanced<
https://github.com/wistcc/werewolf-moderator/pull/19#issuecomment-292734014

2017-04-08 17:43 UTC, wOvalle commented on src/js/pages/Home.js
> +              <button onClick={this.props.startGame.bind(this, "chaos")} className="btn btn-default col-md-5"><i class="fa fa-arrows" aria-hidden="true"></i> Quick Chaos</button>
https://github.com/wistcc/werewolf-moderator/pull/19#issuecomment-292734014

2017-04-08 17:43 UTC, wOvalle commented on src/js/pages/Cards.js
> +              <button onClick={this.props.startGame.bind(this, "balanced")} className="btn btn-default col-md-4 col-md-offset-1 col-xs-12 btn-space"><i class="fa fa-balance-scale" aria-hidden="true">
https://github.com/wistcc/werewolf-moderator/pull/19#issuecomment-292734014

2017-04-08 17:44 UTC, wOvalle commented on src/js/pages/Cards.js
> +              <button onClick={this.props.startGame.bind(this, "chaos")} className="btn btn-default col-md-4 col-md-offset-1 col-xs-12 btn-space"><i class="fa fa-arrows" aria-hidden="true"></i> Quick
https://github.com/wistcc/werewolf-moderator/pull/19#issuecomment-292734014

2017-04-08 17:44 UTC, wOvalle commented on src/js/components/Wizard.js
> +const DEFAULT_GAME_MODE = 'balanced';
https://github.com/wistcc/werewolf-moderator/pull/19#issuecomment-292734014

2017-04-08 17:52 UTC, wistcc commented on src/js/components/Wizard.js
> +        value: 1,
This `1` hardcoded?

2017-04-08 17:52 UTC, wistcc approved these changes

2017-04-08 18:18 UTC, wOvalle commented on src/js/components/Wizard.js
> +        value: 1,
Actually, that's required to be hardcoded (for now). That's the initial amount that a card will have. In order to remove this hardcode number we should have a centralized storage of cards amount (yes, this actually exists in the werewolf brain but the api doesn't return cards amounts).

2017-04-10 22:38 UTC, merged